trigger:
- none

pool:
  vmImage: 'windows-latets'

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'release'
  solution: '**/HelloWorldApp.sln'
  project: '**/HelloWorldApp.csproj'

steps:
- task: NuGetToolInstaller@1
  name: 'NugetToolInstaller'
  displayName: 'Nuget Tool Installer'

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '$(solution)'
    feedsToUse: 'select'